services:
  pnid-app:
    build:
      context: .
      dockerfile: Dockerfile
      # Add specific buildx platform for consistency
      args:
        - BUILDPLATFORM=linux/amd64
    env_file: .env.local
    environment:
      - NODE_ENV=development
    depends_on:
      metadata-parser:
        condition: service_healthy
      pdf-export:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      # For development: mount source code for hot reloading
      - ./:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  metadata-parser:
    build:
      context: ./companion/metadata-parser
      dockerfile: Dockerfile
    env_file: .env.local
    environment:
      - NODE_ENV=development
      - USE_HTTPS=false
      - PORT=5000
      - SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "7123:5000"
    volumes:
      - ./companion/metadata-parser:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  pdf-export:
    build:
      context: ./companion/pdf-export
      dockerfile: Dockerfile
    env_file: .env.local
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "6123:5000"
    volumes:
      - ./companion/pdf-export:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s