FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml* ./
RUN --mount=type=cache,target=/root/.pnpm-store pnpm install --frozen-lockfile

COPY . .

ENV HOST_IP=host.docker.internal

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]