services:
  pnid-app:
    build:
      context: .
      dockerfile: Dockerfile
      # Add specific buildx platform for consistency
      args:
        - BUILDPLATFORM=linux/amd64
    env_file: .env.local
    environment:
      - NODE_ENV=development
    depends_on:
      metadata-parser:
        condition: service_healthy
      pdf-export:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      # For development: mount source code for hot reloading
      - ./:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  
  metadata-parser:
    build:
      context: ./companion/metadata-parser
      dockerfile: Dockerfile
    env_file: .env.local
    environment:
      - NODE_ENV=development
      - USE_HTTPS=false
      - PORT=5000
      - SUPABASE_URL=http://192.168.1.147:54321
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - OPENAI_API_KEY=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
    ports:
      - "7123:5000"
    volumes:
      - ./companion/metadata-parser:/app
      - /app/node_modules
    command: ["pnpm", "dev"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  pdf-export:
    build:
      context: ./companion/pdf-export
      dockerfile: Dockerfile
    env_file: .env.local
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "6123:5000"
    volumes:
      - ./companion/pdf-export:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s