services:
  pnid-app:
    image: ${DOCKERHUB_USERNAME}/pnid-app:latest
    env_file: .env.production
    environment:
      - NODE_ENV=production
    depends_on:
      metadata-parser:
        condition: service_healthy
      pdf-export:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  
  metadata-parser:
    image: ${DOCKERHUB_USERNAME}/metadata-parser:latest
    env_file: .env.production
    environment:
      - NODE_ENV=production
      - USE_HTTPS=false
      - PORT=5000
    ports:
      - "7123:5000"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  pdf-export:
    image: ${DOCKERHUB_USERNAME}/pdf-export:latest
    env_file: .env.production
    environment:
      - PORT=5000
    ports:
      - "6123:5000"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M